spring.application.name=HawkStackSecureAPI
spring.datasource.url=jdbc:mysql://localhost:3306/hawkstackdb
spring.datasource.username=root
spring.datasource.password=admin

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

# JWT  \u2190 ADD THESE
app.jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjcmV0IGtleSBmb3IgSldUIHRva2VucyEhISE=
app.jwt.expiration-ms=86400000

# File Upload  \u2190 ADD THESE
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
app.upload.dir=uploads